# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# specific path build
trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self
  persistCredentials: true
  
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: python -m pip install requests
  displayName: 'Install requests'
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'Stepscreaterecordsalesforce.py'
    arguments: 'olumide.akinwande@bp.com.community.gptdev 0lum1dE£4%2014 3MVG95AcBeaB55lVC4ph4E3buPW7Texcr7qDeNnXA47bwtTa3W0hIKb5dZf9CCnnZuvkmjQKbOYBzExCAre0N E0D79A342987B8F876EB8E7BE3A889AC49726C006E09646BF031D1DA00C5666D'